# Generated by Django 4.2.11 on 2024-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
