# Generated by Django 4.2.11 on 2024-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donals', '0002_alter_productorder_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('email', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
